# Generated by Django 3.0.5 on 2021-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='downloadlink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='projectposter/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='shortdescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
