# Generated by Django 3.0.5 on 2021-09-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_auto_20210901_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='longnameurl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
