# Generated by Django 3.0.5 on 2021-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_auto_20210905_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='htmlpage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
